# -*- coding: utf-8 -*-
"""TRABAJO DE STREAMLIT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13rzUyIdfb2kWsJO2nEZQLLjVU2tfqCsB
"""

import streamlit as st
from PIL import Image

# Configuración de la página
st.set_page_config(page_title="Portafolio de Gabriela", page_icon=":sparkles:", layout="wide")

# Cargar imagen de perfil (opcional)
# Asegúrate de tener "perfil.png" en la misma carpeta o cambia el nombre
try:
    img = Image.open("perfil.png")
    st.image(img, width=200)
except:
    st.warning("Agrega una imagen llamada 'perfil.png' para mostrar tu foto.")

# Título y descripción
st.title("Gabriela del Castillo")
st.subheader("Comunicadora | Desarrolladora Creativa | Creadora de Contenidos")

st.markdown("""
¡Hola! Bienvenida/o a mi portafolio interactivo.

Me dedico a crear proyectos que combinan tecnología, narrativa visual y diseño digital. Aquí podrás ver algunos de mis trabajos destacados, mis habilidades y cómo contactarme.
""")

# Línea divisoria
st.markdown("---")

# Sección de proyectos
st.header("🚀 Proyectos Destacados")

col1, col2 = st.columns(2)

with col1:
    st.subheader("🎬 Documental Interactivo")
    st.markdown("Un proyecto que mezcla storytelling y tecnología para visibilizar historias reales.")
    st.markdown("[Ver proyecto](https://mi-proyecto1.com)")

with col2:
    st.subheader("💻 Chatbox de Personajes de Cine")
    st.markdown("App conversacional que analiza tu personalidad y la compara con personajes de películas.")
    st.markdown("[Ver proyecto](https://mi-proyecto2.com)")

# Otra división
st.markdown("---")

# Habilidades
st.header("🛠️ Habilidades")
st.markdown("""
- **Lenguajes:** Python, HTML, CSS
- **Frameworks:** Streamlit, Flask
- **Creatividad:** Storytelling, diseño de interfaz, escritura narrativa
- **Otras:** Producción audiovisual, comunicación digital, escritura académica
""")

# Contacto
st.markdown("---")
st.header("📫 Contacto")

st.markdown("""
- Email: gabriela@email.com
- LinkedIn: [linkedin.com/in/tuusuario](https://linkedin.com/in/tuusuario)
- GitHub: [github.com/tuusuario](https://github.com/tuusuario)
""")

st.markdown("> Gracias por visitar mi portafolio 💫")